apiVersion: v1
kind: Service
metadata:
  name: fy-devops-mysql
  labels:
    app: fy-devops-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: fy-devops-mysql