apiVersion: v1
kind: Service
metadata:
  labels:
    app: testweb
  name: testweb
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31910
      protocol: TCP
  selector:
    app: testweb

